spring:
  h2:
    console:
      enabled: true
      path: /coupon

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./coupon
    username: coupon
    password:

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    root: info
    org:
      hibernate:
        sql: debug
        type: trace